config/routes.rb
Wines::Application.routes.draw do
	get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  resources :sessions

  get "sign_up" => "users#new", :as => "sign_up"
  
  get "user_tour" => "users#show", :as => "user_tour"
  
  resources :users

  resources :wineries

  root :to => "home#index"
  
  match 'about' => "home#about"
 	match 'tour' => "home#tour"
 	

end

app/models/user.rb
class User < ActiveRecord::Base
	
	has_and_belongs_to_many :wineries
	
	attr_accessible :email, :password, :password_confirmation
	
	attr_accessor :password
	
	before_save :encrypt_password
	
	validates_confirmation_of :password
	validates_presence_of :password, :on => :create
	validates_presence_of :email, :password_confirmation
	validates_uniqueness_of :email
	
	def self.authenticate(email, password)
		user = find_by_email(email)
		if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
			user
		else
			nil
		end
	end
	
	def encrypt_password
		if password.present?
			self.password_salt = BCrypt::Engine.generate_salt
			self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
		end
	end

end

app/models/users_wineries.rb
class UsersWineries < ActiveRecord::Base
end

app/models/winery.rb
class Winery < ActiveRecord::Base
	has_and_belongs_to_many :users
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  helper_method :current_user
  
#  def login_required
#    if session[:user]
#      return true
#    end
#    flash[:warning]='Please login to continue'
#    session[:return_to]=request.request_uri
#    redirect_to :controller => "user", :action => "login"
#    return false 
#  end
	
	private
	
  def current_user
   @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  
  def about
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
 	
 	def create
 		user = User.authenticate(params[:email], params[:password])
 		if user
 			session[:user_id] = user.id
 			redirect_to root_url, :notice => "Log in successful!"
 		else
 			flash.now.alert = "Invalid email/password combination."
 			render "new"
 		end
 	end
 	
 	def destroy
 		session[:user_id] = nil
 		redirect_to root_url, :notice => "Log out successful!"
 	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 	def show
  	user = session[:user_id]
  	
  	if user
  		@user = User.find(user)
  		respond_to do |format|
  		  format.html # index.html.erb
  		  format.json { render :json => @user }
  		end
  	else
  		redirect_to root_url, :notice => "You're not logged in!"
  	end
  	
  	
  end
  
  # new user instance
  def new
  	@user = User.new
  end
  
  # create a new user
  def create
  	@user = User.new(params[:user])
  	if @user.save
  		redirect_to root_url, :notice => "Signed up!"
  	else
  		render "new"
  	end
  end
end

app/controllers/wineries_controller.rb
class WineriesController < ApplicationController
  # GET /wineries
  # GET /wineries.json
  def index
  	@wineries = Winery.paginate(:page => params[:page], :per_page => 10)
  	
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @wineries }
    end
  end

  # GET /wineries/1
  # GET /wineries/1.json
  def show
    @winery = Winery.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @winery }
    end
  end

  # GET /wineries/new/?id=1
  # GET /wineries/new/?id=1.json
  def new
  	user = session[:user_id]
  	
  	if user
  
    	@winery = Winery.find(params[:id])
    	@user = User.find(user)
    	
    	if @user.wineries.include?(@winery)
    		
    		redirect_to winery_path(@winery.id), :notice => "Already part of your tour!"
    		
    	else
    	
    		@user.wineries << @winery
    		redirect_to winery_path(@winery.id), :notice => "Added to your tour list!"
    	
    	end
    	
		else 
		
			redirect_to root_url, :notice => "You're not logged in!"
			
    end
  end

  # GET /wineries/1/edit
  def edit
    @winery = Winery.find(params[:id])
  end

  # POST /wineries
  # POST /wineries.json
  def create
    @winery = Winery.new(params[:winery])

    respond_to do |format|
      if @winery.save
        format.html { redirect_to @winery, :notice => 'Winery was successfully created.' }
        format.json { render :json => @winery, :status => :created, :location => @winery }
      else
        format.html { render :action => "new" }
        format.json { render :json => @winery.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /wineries/1
  # PUT /wineries/1.json
  def update
    @winery = Winery.find(params[:id])

    respond_to do |format|
      if @winery.update_attributes(params[:winery])
        format.html { redirect_to @winery, :notice => 'Winery was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @winery.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /wineries/1
  # DELETE /wineries/1.json
  def destroy
    @winery = Winery.find(params[:id])
    # @winery.destroy
    
    user = session[:user_id]
    
    if user
    	
    	@user = User.find(user)
    
    	@user.wineries.delete(@winery)
    	
    	redirect_to user_path, :notice => "Removed from tour list!"
    
    else
    
    	redirect_to root_url, :notice => "You're not logged in!"
    
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wineries_helper.rb
module WineriesHelper
end

app/views/home/about.html.erb
<h1>About</h1>
<hr>
<br/>
<h4>The General Stuff</h4>
<hr>
<p>The U.S. Winery Database was created by Scott Douglass for the class 'Wines of the World' at Rochester Institute of Technology. It was created to fulfill the project part of the course. The database that is used by this project is populated with 6302 wine producers and blenders that are located within the United States.</p>


<br/><br/>
<h4>The Technical Stuff</h4>
<hr>
<p>This web database application was written using Ruby on Rails v. 3.2.2. It uses a MySQL back-end database to store the information on the wineries. In addition, it uses technologies such as jQuery for some additional features. The layout of the site is done in part through the use of Bootstrap, an open-source UI template built by Twitter. The information gathered on the wineries was acquired from <a href="http://www.factual.com/" target="_blank">www.factual.com</a> and is available there use under the Creative Commons license.</p>

<br/><br/>
<h4>The Personal Stuff</h4>
<hr>
<p>I, at the time of this site's creation, am a fifth-year RIT student majoring in Information Technology with a concentration in Web Development and Database and a minor in Advertising and Public Relations. I will graduate in May, 2012. I also accept freelance work.

app/views/home/index.html.erb
<div id="myCarousel" class="carousel">
  <!-- Carousel items -->
  <div class="carousel-inner">
    <div class="active item">
    	<img src="http://spanishwineexperience.com/EN/img/13.jpg"/>
    	<div class="carousel-caption">
    	  <h4>The United States Winery Database</h4>
    	  <p>Find wineries - in fact, make a day of it.</p>
    	</div>
    </div>
    <div class="item">
    	<img src="http://spanishwineexperience.com/EN/img/04.jpg" />
    	<div class="carousel-caption">
        <h4>Learn Something</h4>
        <p>Find out where the wine you drink comes from or who makes it.</p>
      </div>
    </div>
  </div>
  <!-- Carousel nav -->
  <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
  <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
</div>

<script>

$(document).ready(function() {

	$('.carousel').carousel();
	
});

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>United States Winery Database</title>
  
  <script type="text/javascript" src="https://maps.google.com/maps?file=api&amp;v=2&amp;key=AIzaSyDVkGIvbCfS9J_3w1Se5mMooGDZInKBS_8"></script>
  
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  
  <script src="https://raw.github.com/sbd7514/wines/master/app/assets/javascripts/jquery.gmap-1.1.0-min.js"></script>
  
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
		  <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
		    <span class="icon-bar"></span>
		    <span class="icon-bar"></span>
		    <span class="icon-bar"></span>
		  </a>
		  <a class="brand" href="#">U.S. Winery Database</a>
		  <div class="nav-collapse">
		    <ul class="nav">
		    	<% if current_page?(root_url) %>
		    	  <li class="active"><%= link_to raw('<i class="icon-home icon-white"></i> Home'), {:controller => 'home'}  %></li>
		    	<% else %>
		    		<li><%= link_to raw('<i class="icon-home icon-white"></i> Home'), {:controller => 'home'}  %></li>
		    	<% end %>
		    
					<% if current_page?(wineries_path) %>
					  <li class="active"><%= link_to raw('<i class="icon-glass icon-white"></i> Wineries'), {:controller => 'wineries'}  %></li>
					<% else %>
						<li><%= link_to raw('<i class="icon-glass icon-white"></i> Wineries'), {:controller => 'wineries'}  %></li>
					<% end %>
					
					<% if current_page?(about_path) %>
					  <li class="active"><%= link_to raw('<i class="icon-info-sign icon-white"></i> About'), about_path  %></li>
					<% else %>
						<li><%= link_to raw('<i class="icon-info-sign icon-white"></i> About'), about_path  %></li>
					<% end %>
		    </ul>
		    <ul class="nav pull-right">
		    	<% if current_user %>
		    	
		    		<% if current_page?(user_tour_path) %>
		    		  <li class="active"><%= link_to raw('<i class="icon-road icon-white"></i> My Tour'), user_tour_path %></li>
		    		<% else %>
		    			<li><%= link_to raw('<i class="icon-road icon-white"></i> My Tour'), user_tour_path %></li>
		    		<% end %>
		    		<li><%= link_to "Log out", log_out_path %></li>
		    	<% else %>
		    		<li><%= link_to "Sign up", sign_up_path %></li>
		    		<li><%= link_to "Log in", log_in_path %></li>
		    	<% end %>
		    
		    	
		    </ul>
		  </div><!--/.nav-collapse -->
		</div>
	</div>
</div>

<div style="margin-bottom: 20px;" class="container">

<% flash.each do |name, msg| %>
	<%= content_tag :div, msg, :id => "flash_#{name}", :class=>"alert alert-success" %>
<% end %>

<%= yield %>

</div>

</body>


</html>

app/views/users/index.html.erb
<h1>Users</h1>
<hr>

<table class="table table-striped table-bordered">
  <tr>
  	<th>Email</th>
    
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
  	<td><%= user.email %></td>
    <td><%= link_to 'View Details', User %></td>
  </tr>
<% end %>
</table>



<%= will_paginate @users, :renderer => BootstrapPagination::Rails %>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<br/>



<%= simple_form_for(@user, :html => {:class => 'form-vertical' }) do |f| %>
	
	<p>
		<%= f.input :email %>
	</p>
	<p>
		<%= f.input :password %>
	</p>
	<p>
		<%= f.input :password_confirmation %>
	</p>
		
	<%= f.submit 'Sign Up', :class=>"btn" %>
<% end %> 

app/views/users/show.html.erb
<h1>Winery Tour : <%= @user.email %></h1>
<hr>

<div style="width:  100%; height:  600px;" id="winery-map"></div>

<br/>

<table class="table table-striped table-bordered">
  <tr>
  	<th>Winery</th>
    
    <th></th>
    <th></th>
  </tr>

	<% @user.wineries.each do |winery|  %>
	  <tr>
	  	<td>
		  	<% if winery.operating_name.empty? %>
		  		<%= winery.owner_name %>
		  	<% else %>
		  		<%= winery.operating_name %>
		  	<% end %>
	  	</td>
	    <td><%= link_to 'View Details', winery %></td>
	    <td><%= link_to 'Remove', winery_path(winery.id), :method => :delete %></td>
	  </tr>
  <% end %>
</table>

<script>

$(document).ready(function() {
	
	$("#winery-map").gMap({ 
		controls: false, scrollwheel: false, 
		markers: [
		<% @user.wineries.each do |winery|  %>
			{ latitude: <%= winery.latitude %>, longitude: <%= winery.longitude %>  },
		<% end %>
		],
	address: "United States",
	zoom: 3
	});
	
});

</script>

app/views/wineries/_form.html.erb
<%= form_for(@winery) do |f| %>
  <% if @winery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@winery.errors.count, "error") %> prohibited this winery from being saved:</h2>

      <ul>
      <% @winery.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :permit_number %><br />
    <%= f.text_field :permit_number %>
  </div>
  <div class="field">
    <%= f.label :owner_name %><br />
    <%= f.text_field :owner_name %>
  </div>
  <div class="field">
    <%= f.label :operating_name %><br />
    <%= f.text_field :operating_name %>
  </div>
  <div class="field">
    <%= f.label :street %><br />
    <%= f.text_field :street %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zip %><br />
    <%= f.text_field :zip %>
  </div>
  <div class="field">
    <%= f.label :zip4 %><br />
    <%= f.text_field :zip4 %>
  </div>
  <div class="field">
    <%= f.label :county %><br />
    <%= f.text_field :county %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/wineries/edit.html.erb
<h1>Editing winery</h1>

<%= render 'form' %>

<%= link_to 'Show', @winery %> |
<%= link_to 'Back', wineries_path %>

app/views/wineries/index.html.erb
<h1>Wineries</h1>
<hr>

<table class="table table-striped table-bordered">
  <tr>
  	<th>State</th>
    <th>Winery Name</th>
    <th>Owner Name</th>
    <th></th>
  </tr>

<% @wineries.each do |winery| %>
  <tr>
  	<td><%= winery.state %></td>
  	<% if winery.operating_name.empty? %>
  		<td><%= winery.owner_name %></td>
  	<% else %>
    	<td><%= winery.operating_name %></td>
    <% end %>
    <td><%= winery.owner_name %></td>
    <td><%= link_to 'View Details', winery %></td>
  </tr>
<% end %>
</table>



<%= will_paginate @wineries, :renderer => BootstrapPagination::Rails %>

<!-- <%= link_to 'New Winery', new_winery_path %> -->

app/views/wineries/new.html.erb
<h1>New winery</h1>

<%= render 'form' %>

<%= link_to 'Back', wineries_path %>

app/views/wineries/show.html.erb
<h1>
<% if @winery.operating_name.empty? %>
	<%= @winery.owner_name %>
<% else %>
	<%= @winery.operating_name %>
<% end %>
<small><%= @winery.city %>, <%= @winery.state %></small>

<span class="pull-right">
	<% if (@winery.id - 1) > 0 %>
		<%= link_to raw('<i class="icon-arrow-left"></i> Previous'), winery_path(@winery.id - 1), :class=> 'btn' %>
	<% end %>
	<% if current_user %>
		<%= link_to raw('<i class="icon-plus-sign icon-white"></i> Add To Tour'), new_winery_path.to_s + "/?id=" + @winery.id.to_s, :class => 'btn btn-success' %>
	<% end %>
	<% if (@winery.id + 1) < 6303 %>
		<%= link_to raw('Next <i class="icon-arrow-right"></i>'), winery_path(@winery.id + 1), :class=> 'btn' %>
	<% end %>
</span>
</h1>
<hr>

<div class="row">
	<div class="span6">
	
		<h5><i class="icon-glass"></i> Winery Information</h5>
		<hr style="margin-top: 5px; margin-bottom: 5px;">
		
		<div class="well">
			Owner: <%= @winery.owner_name %><br/>
			Permit: <%= @winery.permit_number %>
			
			
		</div>
	
	</div>
	<div class="span6">
		
		<h5><i class="icon-map-marker"></i> Location Information</h5>
		<hr style="margin-top: 5px; margin-bottom: 5px;">
		
		<div class="well">
			<%= @winery.street %><br/>
			<%= @winery.city %>, <%= @winery.state %>, <%= @winery.zip %>
		</div>
		
	
	</div>
</div>

<div style="width:  100%; height:  300px;" id="winery-map"></div>

<script>

$(document).ready(function() {
	
	$("#winery-map").gMap({ controls: false, scrollwheel: false, markers: [{ latitude: <%= @winery.latitude %>, longitude: <%= @winery.longitude %> }],
	zoom: 12 
	});
	
});

</script>